---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hakurei Reimu.
--- DateTime: 8/10/2024 下午6:06
---

Hook.Add("Alice.Doll.Controller", "Player.Control.Change", function (client, deltaTime, character, targets)
    if targets[1] == nil then return end

    -- 获取上一次控制的角色
    local lastControlledCharacter = CharacterInfo("LastControlled")

    if CLIENT then
        if lastControlledCharacter then
            Timer.Wait(function()
                -- 将控制权转移到上一个控制的角色
                Character.Controlled = character
            end, 10)
        end
    else
        if lastControlledCharacter then
            Timer.Wait(function()
                -- 在服务器端设置客户端控制的角色为上一个控制的角色
                client.SetClientCharacter(character)
            end, 10)
        end
    end

    return true -- returning true allows us to hide the message
end)

Hook.Add("chatMessage", "examples.humanSpawning", function (message, client)
    if message ~= "!humanspawning" then return end

    -- Note: If we plan only running this server-side, we could grab the CharacterInfo from client instead, which will have all their info already set, like name and hair style.
    local info = CharacterInfo("human", "Robert")
    info.Job = Job(JobPrefab.Get("assistant"))

    local submarine = Submarine.MainSub
    -- This method takes a list of CharacterInfo that it will use to choose the correct spawn waypoint
    -- in this case we only have a single info, so we just create a table with just that info in it.
    local spawnPoint = WayPoint.SelectCrewSpawnPoints({info}, submarine)[1]

    if spawnPoint == nil then
        -- we should probably do something if it isn't able to find a spawn point
    end

    local character = Character.Create(info, spawnPoint.WorldPosition, info.Name, 0, false, false)
    character.TeamID = CharacterTeamType.Team1
    character.GiveJobItems()

    if CLIENT then
        Character.Controlled = character
    else
        client.SetClientCharacter(character)
    end

    return true -- returning true allows us to hide the message
end)